# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['py/installer.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('py/launcher.py', 'py'),
        ('py/server.py', 'py'),
        ('py/ai_classifier.py', 'py'),
        ('py/classifier_features.py', 'py'),
        ('py/classifier_trainer.py', 'py'),
        ('py/restart_helper.py', 'py'),
        ('html/dashboard.html', 'html'),
        ('html/dashboard_modern.html', 'html'),
        ('html/static/classic.css', 'html/static'),
        ('html/static/classic.js', 'html/static'),
        ('html/static/modern.css', 'html/static'),
        ('html/static/modern.js', 'html/static'),
        ('py/pack.py', 'py'),
        ('py/repair_update.py', 'py'),
        ('requirements.txt', '.'),
        ('repair_update.bat', '.'),
        ('更新修复工具.bat', '.'),
        ('start.sh', '.'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='作业追踪器v0.1.1',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
